version: '3.8'

services:
  # 1) NGINX front-end (for manual/dev preview)
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:ro
      - ./dev-only/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - wordpress

  # 2) PHP-FPM + WordPress (for dev preview & tests)
  wordpress:
    image: wordpress:6.8.1-php8.1-fpm-alpine
    volumes:
      - .:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_test
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress_test
    depends_on:
      - db

  # 3) MariaDB for both dev & tests
  db:
    image: mariadb:10.5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: wordpress_test
      MYSQL_USER: wp_test
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

  # 4) PHPUnit container (isolated test runner)
  phpunit:
    build:
      context: .
      dockerfile: Dockerfile.phpunit
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  # 5) Node container (for building/bundling your JS modules)
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - .:/var/www/html
      - /var/www/html/js/node_modules
    working_dir: /var/www/html/js
    command: npm install

volumes:
  db_data:
