name: Test

on:
  workflow_dispatch:

jobs:
  phpunit:
    name: PHPUnit via docker-compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build all images
        run: make build

      - name: Start WordPress & DB
        run: docker-compose up -d wordpress db

      - name: Run tests
        run: make test

      - name: Tear down
        if: always()
        run: docker-compose down
